---
- name: Instalar MariaDB
  apt:
    name: mariadb-server
    state: present

- name: Instalar PyMySQL
  apt:
    name: python3-pymysql
    state: present

- name: Permitir conexiones remotas a MariaDB
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
  notify: Reiniciar MariaDB

- name: Crear base de datos
  community.mysql.mysql_db:
    name: "{{ bd_name }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Crear usuario de base de datos
  community.mysql.mysql_user:
    name: "{{ bd_user }}"
    password: "{{ bd_pass }}"
    priv: "{{ bd_name }}.*:ALL"
    host: "%"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
