network:
  version: 2
  ethernets:
    ens3:
      dhcp4: true              # red NAT con DHCP
    ens4:
      dhcp4: false
      addresses: ["10.0.0.1/24"]  # IP estática en red muy aislada (actúa como gateway)
