---
- name: Instalar apache2
  apt:
    name: apache2
    state: present

- name: Copiar fichero de configuración y reiniciar el servicio
  copy:
    src: apache.conf
    dest: /etc/apache2/conf-available/personalizado.conf
    owner: root
    group: root
    mode: '0644'
  notify: Reiniciar Apache

- name: Desplegar página de inicio
  template:
    src: index.j2
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'
