- name: Configuracion comun
  hosts: all
  become: true
  roles:
    - commons

- name: Configuracion servidor web
  hosts: servidores_web
  become: true
  roles:
    - apache2

- name: Configuracion servidor bd
  hosts: servidores_bd
  become: true
  roles:
    - mariadb
